name: Feedback
description: There is something I think you should be thinking about...
title: "[Feedback]: "
labels: ["feedback"]
assignees: []
projects: ["astro-otter/1"]

body:
- type: markdown
  attributes:
    value: |
      Thanks for being willing to contribute your feedback to OTTER! Please make sure you have checked closed issues and fill out the following information:
    
- type: textarea
  id: description
  attributes:
    label: "Describe the Feature"
    description: |
      "What is missing? Why is it needed? Any tips on implementation? Please provide a minimum working example demonstrating where you want it to fit in."

- type: markdown
  attributes:
    value: Thanks again for filling out this feedback form! We will respond with our thoughts as soon as possible!
